repos:
  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform-docs
        language: docker_image
        entry: quay.io/terraform-docs/terraform-docs:latest
        args: ["markdown", ".","--output-file", "README.md"]
        pass_filenames: false
