################################
#           Snowflake
################################

variable "idp_certificate" {
  description = "(Optional) The certificate used to verify SAML assertions from the IdP being used with Snowflake. Enter this value as a one-line string with literal new line characters (\\n) specifying the line breaks."
  type        = string
  default     = ""
}

variable "idp_sso_login_url" {
  description = "(Optional) The IdP SSO URL for the IdP being used with Snowflake."
  type        = string
  default     = ""
}

variable "load_balancer_certificate_arn" {
  description = "(Optional) ARN of SSL certificate that will be used for client connections to Snowflake."
  type        = string
  default     = ""
}

variable "sidecar_public_idp_certificate" {
  description = "(Optional) The public certificate used to verify signatures for SAML Assertions generated by the sidecar. Enter this value as a one-line string with literal new line characters (\n) specifying the line breaks."
  type        = string
  default     = ""
}

variable "sidecar_private_idp_key" {
  description = "(Optional) The private key used to sign SAML Assertions generated by the sidecar. Enter this value as a one-line string with literal new line characters (\n) specifying the line breaks."
  type        = string
  default     = ""
}
