name: Check

on:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check zip file
        run: |
          zip_sha=$(sha256sum files/self-signed-certificate-lambda.zip | awk '{print $1}')
          zip_sha_from_code=$(cat files/self-signed-certificate-lambda-hash.txt)
          test $zip_sha = $zip_sha_from_code || exit 10
